### ISSUE TITLE
Support for linux/arm64 wheels

### ISSUE THREAD

**Issue by gaby** [jllllll/llama-cpp-python-cuBLAS-wheels#29]
Hey @jllllll I manage to figure out how to use github to build linux/arm64 wheels. Is this something that could be added to your repo?

```yaml
name: Build Wheels

on: [push, pull_request]

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: 'v0.2.20'
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        run: CIBW_SKIP="*musllinux* pp*" CIBW_REPAIR_WHEEL_COMMAND="" cibuildwheel --platform linux --archs "aarch64" --output-dir wheelhouse
      - name: List wheelhouse contents
        run: ls -la wheelhouse/
```

The whole CI takes around 21 mins to run and generates these:

```console
14:23 llama_cpp_python-0 .2.20- cp31 0- cp310- manylinux_2_17_aarch64. whl
-rW-r- -r--
14:27 llama_cpp_python-0.2. 20-cp311-cp311 - manylinux_2__17_aarch64.whl
-rW-r- -r--
14:31 1llama_cpp_python-0.2.20- cp31 2-cp312- manylinux_2_17_aarch64. whl
14:15 llama_cpp_python-0.2. 20-cp38-cp38- manylinux_2_17_aarch64. whl
-rW-- -r--
14:191lama_cpp_python- 0. 2. 20-cp39- cp39 - manylinux_2_17_aarch64.whl
```

This would allow raspberry pi's and macos using linux to install wheels.
